name: Build documentation

on:
  push:
    branches: master

jobs:
  docs:
    name: Build documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundler-cache: true
      - name: Install Ruby Sass (deprecated)
        run: gem install sass
      - name: Install Sass Convert globally
        run: npm i -g sass-convert
      - name: Install Sass Doc
        run: npm i sassdoc
      - name: Install Gulp
        run: npm i gulp
      - name: Install & Build 🔧
        run: npm i && npm run build-sass
      - name: Build docs
        run: gulp docs
      - name: Commit files
        run: |
          git config --local user.email "537310+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -a -m "Upload documentation"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
