name: Build documentation

on:
  release:
    types: [published]

jobs:
  docs:
    name: Generate SassDoc Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'
          bundler-cache: true

      - name: Setup Sass
        run: gem install sass

      - name: Install & Build
        run: npm i && npm run build

      - name: Generate SassDoc documentation
        run: npx sassdoc dist/sass --dest docs/

      - name: Deploy documentation to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          publish_branch: doc
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
