name: Build style

on:
  push:
    branches: master

jobs:
  build:
    name: Build style
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '12.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Install & Build 🔧
        run: npm i && npm run build
  docs:
    name: Build documentation
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/[0-9]+.[0-9]+.[0-9]+')
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '12.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Install & Build 🔧
        run: npm i && npm run build
      - name: Build docs
        run: npm run build-docs
