name: Build style

on:
  push:
    branches: master

jobs:
  build:
    name: Build style
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Install & Build 🔧
        run: npm i && npm run build
  docs:
    name: Build documentation
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundler-cache: true
      - name: Install Ruby Sass (deprecated)
        run: gem install sass
      - name: Install Sass Convert globally
        run: npm i -g sass-convert
      - name: Install Sass Doc globally
        run: npm i -g sassdoc
      - name: Install Gulp globally
        run: npm i -g gulp
      - name: Install & Build 🔧
        run: npm i && npm run build-sass
      - name: Build docs
        run: gulp docs
